### DISCUSSION TITLE
Not working in `links` of about page

### DISCUSSION THREAD

**Discussion by stefanocoretta** [mcanouil/quarto-iconify#60] [Q&A]
Hi! Thanks for creating this extension. :) I tried using it with the links of the About page, but it seems not to be working.

```yaml
about:
  template: trestles
  image-width: 10em
  image-shape: round
  links:
    - icon: "{{< iconify academicons osf-square >}}"
      text: OSF
      href: https://osf.io/
```

Renders as:

```html
<i class="bi bi-{{< iconify academicons osf-square >}}"></i>
```

(but works fine everywhere else)
