### ISSUE TITLE
Would like this extension to work with the sidebar of a book project

### ISSUE THREAD

**Issue by ercbk** [mcanouil/quarto-iconify#9]
Saw in quarto issue "How to use custom icons?" ([#5816](https://github.com/quarto-dev/quarto-cli/discussions/5816)) that this extension worked with the navbar of websites. I tried to get this work with the website sidebar of a book project, but I couldn't get the icon to appear.

```
book:
  sidebar: 
     tools: 
        - text: "{{< iconify fa6-regular heart >}}"
          href: https://ercbk.github.io/Statistical-Rethinking-Notebook/
```

I tried using "icon" instead of "text," but that doesn't work either. I also inserted the shortcode in one of HTML documents in the project, and it worked there. So, I figure the extension is installed correctly.  
Anyways, I was wondering if it was possible to make this extension work with the website sidebar of quarto book projects. Thank you.
